apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config-staging
  namespace: staging
data:
  FLASK_ENV: "staging"
  DATABASE_URL: "postgresql://postgres:Password1.@postgres-staging:5432/db"
  settings.cfg: |
    # Staging-specific settings
    LOG_LEVEL=DEBUG
    DB_HOST=staging-db.internal