services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password1.
    ports:
      - 5432:5432
    networks:
      backend:
        ipv4_address: 172.16.241.11

  app:
    image: registry.internal.uia.no/ikt206-g-25v-devops/group27/exam
    ports:
      - 5000:5000
    environment:
      APP_MODE: "staging"
      POSTGRES_HOST: "172.16.241.11"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password1."
    networks:
      backend:
        ipv4_address: 172.16.241.9
    depends_on:
      - db

networks:
  backend:
    name: backend
    ipam:
      driver: default
      config:
        - subnet: "172.16.241.0/24"

